quarkus.http.auth.permission.public.policy=permit

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.datasource.password=sa
quarkus.datasource.username=

quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false