## SIMULACAO
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.datasource.password=sa
quarkus.datasource.username=
quarkus.hibernate-orm.packages=org.caixa.model.entity.loan
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

## PRODUTO
quarkus.datasource.product.db-kind=${DB-KIND:mssql}
quarkus.datasource.product.jdbc.url=${JDBC_URL:jdbc:sqlserver://dbhackathon.database.windows.net:1433;databaseName=hack}
quarkus.datasource.product.username=${DATASOURCE_USERNAME:hack}
quarkus.datasource.product.password=${DATASOURCE_PASSWORD:Password23}
quarkus.hibernate-orm."product".datasource=product
quarkus.hibernate-orm."product".packages=org.caixa.model.entity.product
quarkus.hibernate-orm."product".database.default-schema=dbo

quarkus.hibernate-orm.log.sql=true

quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.default-locale=pt-BR
%dev.quarkus.datasource.dev-ui.allow-sql=true
